package:
  name: torch_snippets
  version: '0.530'
source:
  sha256: b0c5de8108d4ec175ec40b73dcfd0e8cec29c0e83171cec8aaeb865f9200f696
  url: https://files.pythonhosted.org/packages/33/29/ec172cc92aaf82303a25784f9470114ed76acfd52b734a1a9cfd93d20c64/torch_snippets-0.530.tar.gz
about:
  description: "# Utilities for simple needs\n\n\n\n## torch snippets does a lot of\
    \ default importing for you\nWhether it is numpy, pandas, matplotlib or the useful\
    \ functions that are mentioned below\nSimply call\n```python\nfrom torch_snippets\
    \ import *\n```\nAll the imports are lightweight and thus should not take more\
    \ than a couple of seconds\n\n## Auxiliary Functions\nThere are simple functions\
    \ that are overloaded to take inputs and perform repetitive tasks that usually\
    \ take a few lines to write\n\n#### Images\n`show`, `inspect`, `Glob`, `read`,\
    \ `resize`, `rotate`\n\n#### Files and Paths\n`stem`, `Glob`, `parent`, `name`,\
    \ `fname`,\n\n\n`makedir`, `zip_files`, `unzip_file`,\n\n\n`find`, `extn`,\n\n\
    \n`readlines`, `writelines`\n\n#### Lists\n`L`, `flatten`\n\n#### Dump and load\
    \ python objects\n`loaddill`,`dumpdill`\n\n#### Misc\n`Tqdm`, `Timer`, `randint`,\
    \ `Logger`\n\n#### Sets\n`unique`, `diff`, `choose`, `common`\n\n#### Pytorch\
    \ Modules\n`Reshape` and `Permute` (`nn.Modules`)\n\n#### Report as Pytorch Lightning\
    \ Callback\n`LightningReport`\n\n#### Charts\n`Chart` from altair\n\nand many\
    \ more to come...\n\n## Install\n`pip install torch_snippets`\n\n## Usage\n\n\n\
    ```python\n%time from torch_snippets import *\n```\n\n    CPU times: user 1.79\
    \ s, sys: 672 ms, total: 2.46 s\n    Wall time: 2.62 s\n\n\n```python\ndir()\n\
    ```\n\n\n\n\n    ['AttrDict',\n     'B',\n     'BB',\n     'Blank',\n     'C',\n\
    \     'Chart',\n     'DataLoader',\n     'Dataset',\n     'Debug',\n     'E',\n\
    \     'Excep',\n     'F',\n     'Float',\n     'Glob',\n     'Image',\n     'ImportEnum',\n\
    \     'In',\n     'Inf',\n     'Info',\n     'Int',\n     'L',\n     'LightningReport',\n\
    \     'NullType',\n     'Out',\n     'P',\n     'PIL',\n     'Path',\n     'Permute',\n\
    \     'PrettyString',\n     'Report',\n     'Reshape',\n     'Self',\n     'ShowPrint',\n\
    \     'Stateful',\n     'Str',\n     'StrEnum',\n     'T',\n     'Timer',\n  \
    \   'Tqdm',\n     'Warn',\n     '_',\n     '__',\n     '___',\n     '__builtin__',\n\
    \     '__builtins__',\n     '__doc__',\n     '__loader__',\n     '__name__',\n\
    \     '__package__',\n     '__spec__',\n     '_dh',\n     '_i',\n     '_i1',\n\
    \     '_i2',\n     '_ih',\n     '_ii',\n     '_iii',\n     '_oh',\n     'add',\n\
    \     'add_props',\n     'alt',\n     'anno_ret',\n     'annotations',\n     'arg0',\n\
    \     'arg1',\n     'arg2',\n     'arg3',\n     'arg4',\n     'argnames',\n  \
    \   'argwhere',\n     'attrdict',\n     'basic_repr',\n     'bbfy',\n     'bind',\n\
    \     'camel2snake',\n     'charts',\n     'choose',\n     'chunked',\n     'class2attr',\n\
    \     'common',\n     'compose',\n     'copy_func',\n     'crop_from_bb',\n  \
    \   'custom_dir',\n     'cv2',\n     'cycle',\n     'defaults',\n     'detuplify',\n\
    \     'device',\n     'df2bbs',\n     'diff',\n     'display',\n     'dumpdill',\n\
    \     'enlarge_bbs',\n     'eq',\n     'even_mults',\n     'exec_local',\n   \
    \  'exit',\n     'extn',\n     'fastcores',\n     'fastuple',\n     'filter_dict',\n\
    \     'filter_ex',\n     'filter_keys',\n     'filter_values',\n     'find',\n\
    \     'first',\n     'flatten',\n     'fname',\n     'fname2',\n     'ge',\n \
    \    'gen',\n     'get_class',\n     'get_ipython',\n     'getattrs',\n     'glob',\n\
    \     'groupby',\n     'gt',\n     'hasattrs',\n     'ifnone',\n     'ignore_exceptions',\n\
    \     'in_',\n     'inspect',\n     'instantiate',\n     'inum_methods',\n   \
    \  'is_',\n     'is_array',\n     'is_not',\n     'isdir',\n     'jitter',\n \
    \    'last_index',\n     'le',\n     'line',\n     'lines',\n     'listify',\n\
    \     'load_torch_model_weights_to',\n     'loaddill',\n     'loader',\n     'logger',\n\
    \     'lt',\n     'lzip',\n     'makedir',\n     'map_ex',\n     'maps',\n   \
    \  'maybe_attr',\n     'md5',\n     'merge',\n     'mk_class',\n     'mul',\n\
    \     'ne',\n     'nested_attr',\n     'nested_idx',\n     'nn',\n     'not_',\n\
    \     'now',\n     'np',\n     'null',\n     'num_cpus',\n     'num_methods',\n\
    \     'nunique',\n     'optim',\n     'os',\n     'otherwise',\n     'pad',\n\
    \     'parent',\n     'partialler',\n     'patch',\n     'patch_property',\n \
    \    'patch_to',\n     'pd',\n     'pdb',\n     'pdfilter',\n     'pl',\n    \
    \ 'plt',\n     'properties',\n     'puttext',\n     'quit',\n     'rand',\n  \
    \   'randint',\n     'range_of',\n     're',\n     'read',\n     'readPIL',\n\
    \     'readlines',\n     'rect',\n     'remove_duplicates',\n     'rename_batch',\n\
    \     'renumerate',\n     'replicate',\n     'resize',\n     'risinstance',\n\
    \     'rnum_methods',\n     'rotate',\n     'save_torch_model_weights_from',\n\
    \     'see',\n     'set_logging_level',\n     'setattrs',\n     'setify',\n  \
    \   'show',\n     'shrink_bbs',\n     'snake2camel',\n     'sorted_ex',\n    \
    \ 'stem',\n     'stems',\n     'stop',\n     'store_attr',\n     'str_enum',\n\
    \     'sub',\n     'subplots',\n     'sys',\n     'th',\n     'to_absolute',\n\
    \     'to_relative',\n     'tonull',\n     'torch',\n     'torch_loader',\n  \
    \   'torchvision',\n     'tqdm',\n     'trange',\n     'transforms',\n     'true',\n\
    \     'truediv',\n     'try_attrs',\n     'tuplify',\n     'type_hints',\n   \
    \  'typed',\n     'uint',\n     'unique',\n     'uniqueify',\n     'unzip_file',\n\
    \     'using_attr',\n     'val2idx',\n     'with_cast',\n     'wrap_class',\n\
    \     'write',\n     'writelines',\n     'xywh2xyXY',\n     'zip_cycle',\n   \
    \  'zip_files']\n"
  dev_url: https://github.com/sizhky/torch_snippets/tree/master/
  doc_url: https://sizhky.github.io/torch_snippets/
  home: https://github.com/sizhky/torch_snippets/tree/master/
  license: Apache Software
  license_family: APACHE
  summary: One line functions for common tasks
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - sizhky
requirements:
  host:
  - pip
  - python
  - packaging
  - fastcore
  - matplotlib
  - Pillow
  - altair
  - dill
  - ipython
  - loguru
  - numpy
  - pandas
  - tqdm
  - rich
  - PyYAML
  - catalogue
  - confection
  - pydantic
  - typing
  - srsly
  - typing_extensions
  - wasabi
  - jsonlines
  - imgaug>=0.4.0
  - xmltodict
  - fuzzywuzzy
  - scikit-learn
  - nltk
  - python-Levenshtein
  - pre-commit
  - pymupdf
  - nbconvert
  - nbformat
  - icecream
  run:
  - pip
  - python
  - packaging
  - fastcore
  - matplotlib
  - Pillow
  - altair
  - dill
  - ipython
  - loguru
  - numpy
  - pandas
  - tqdm
  - rich
  - PyYAML
  - catalogue
  - confection
  - pydantic
  - typing
  - srsly
  - typing_extensions
  - wasabi
  - jsonlines
  - imgaug>=0.4.0
  - xmltodict
  - fuzzywuzzy
  - scikit-learn
  - nltk
  - python-Levenshtein
  - pre-commit
  - pymupdf
  - nbconvert
  - nbformat
  - icecream
test:
  imports:
  - torch_snippets
